name: Repository Settings

on:
  push:
    branches:
      - main

jobs:
  set_settings:
    runs-on: ubuntu-latest
    steps:
      - name: Configure repository settings
        run: |
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_ADMINISTRATION_WRITE }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }} \
            -d '{
              "has_projects": false,
              "has_wiki": false,
              "allow_auto_merge": true,
              "delete_branch_on_merge": true
            }'

      - name: Set up `main` branch protection
        run: |
          curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_ADMINISTRATION_WRITE }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/branches/main/protection \
            -d '{
              "required_status_checks": {
                "strict": true,
                "contexts": []
              },
              "enforce_admins": false,
              "required_pull_request_reviews": {
                "dismiss_stale_reviews": false,
                "require_code_owner_reviews": true
              },
              "restrictions": null
            }'

      - name: Set up `release` branch protection
        run: |
          curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_ADMINISTRATION_WRITE }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/branches/release/**/protection \
            -d '{
              "required_status_checks": {
                "strict": true,
                "contexts": []
              },
              "enforce_admins": true,
              "required_pull_request_reviews": {
                "dismiss_stale_reviews": false,
                "require_code_owner_reviews": true,
                "require_last_push_approval": true
              },
              "restrictions": null
            }'
